import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./styles.css";
import Card from "../components/Card/Card";
import Navbar from "@/components/Navbar";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const systems = [
  {
    title: "Dealernet",
    description: "Acesse o sistema Dealernet para gerenciar suas operações.",
    image: "/dealernet_ (1).svg",
    link: "https://toriba.dealernetworkflow.com.br/",
  },
  {
    title: "Vianuvem",
    description: "Acesse o sistema Vianuvem para controle de frotas.",
    image: "/logo-unico-color.svg",
    link: "https://app.vianuvem.com.br/",
  },
  {
    title: "Fandi",
    description: "Acesse o sistema Vianuvem para controle de frotas.",
    image: "/logo_fandi.png",
    link: "https://app.fandi.com.br/",
  },
  {
    title: "Vianuvem",
    description: "Acesse o sistema Vianuvem para controle de frotas.",
    image: "/logo-unico-color.svg",
    link: "https://app.vianuvem.com.br/",
  },
  {
    title: "Vianuvem",
    description: "Acesse o sistema Vianuvem para controle de frotas.",
    image: "/logo-unico-color.svg",
    link: "https://app.vianuvem.com.br/",
  },
  {
    title: "Vianuvem",
    description: "Acesse o sistema Vianuvem para controle de frotas.",
    image: "/logo-unico-color.svg",
    link: "https://app.vianuvem.com.br/",
  },
  {
    title: "Vianuvem",
    description: "Acesse o sistema Vianuvem para controle de frotas.",
    image: "/logo-unico-color.svg",
    link: "https://app.vianuvem.com.br/",
  },
  // Adicione outros sistemas aqui
];

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <Navbar />

        <div
          style={{
            display: "flex",
            gap: "16px",
            flexWrap: "wrap",
            justifyContent: "center",
            padding: "16px",
            backgroundColor: "#f8f9fa",
          }}
        >
          {systems.map((system, index) => (
            <Card
              key={index}
              title={system.title}
              description={system.description}
              image={system.image}
              link={system.link}
            />
          ))}
        </div>

        {children}
      </body>
    </html>
  );
}
